version: '3.1'
services:
  eureka-server1:
    restart: always
    image: 192.168.109.128:5000/egrand-wfw-eureka:1.1-SNAPSHOT
    container_name: eureka-server1
    networks:
      - eureka-net
    ports:
      - 19001:19001
    environment:
      - spring.profiles.active=eureka-server1

  eureka-server2:
    restart: always
    image: 192.168.109.128:5000/egrand-wfw-eureka:1.1-SNAPSHOT
    container_name: eureka-server2
    networks:
      - eureka-net
    ports:
      - 19002:19002
    environment:
      - spring.profiles.active=eureka-server2

  eureka-server3:
    restart: always
    image: 192.168.109.128:5000/egrand-wfw-eureka:1.1-SNAPSHOT
    container_name: eureka-server3
    networks:
      - eureka-net
    ports:
      - 19003:19003
    environment:
      - spring.profiles.active=eureka-server3
networks:
  eureka-net:
    driver: bridge